#jdbcUrl=jdbc:mysql://localhost:3306/board_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
jdbcUrl=jdbc:mysql://dain2.iptime.org:3306/board_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

#username=user1
username=user2

password=1111
maximumPoolSize=10
minimumIdle=5
connectionTimeout=30000
idleTimeout=600000